// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID              pgtype.UUID        `json:"id"`
	Url             string             `json:"url"`
	Status          string             `json:"status"`
	DownloadedBytes int64              `json:"downloaded_bytes"`
	TotalBytes      pgtype.Int8        `json:"total_bytes"`
	ObjectKey       pgtype.Text        `json:"object_key"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
