// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (url)
VALUES ($1)
RETURNING id, url, status, downloaded_bytes, total_bytes, object_key, error_message, created_at, updated_at
`

func (q *Queries) CreateJob(ctx context.Context, url string) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, url)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Status,
		&i.DownloadedBytes,
		&i.TotalBytes,
		&i.ObjectKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, url, status, downloaded_bytes, total_bytes, object_key, error_message, created_at, updated_at FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Status,
		&i.DownloadedBytes,
		&i.TotalBytes,
		&i.ObjectKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDone = `-- name: MarkDone :exec
UPDATE jobs
SET status = 'done',
    object_key = $2,
    updated_at = now()
WHERE id = $1
`

type MarkDoneParams struct {
	ID        pgtype.UUID `json:"id"`
	ObjectKey pgtype.Text `json:"object_key"`
}

func (q *Queries) MarkDone(ctx context.Context, arg MarkDoneParams) error {
	_, err := q.db.Exec(ctx, markDone, arg.ID, arg.ObjectKey)
	return err
}

const markFailed = `-- name: MarkFailed :exec
UPDATE jobs
SET status = 'failed',
    error_message = $2,
    updated_at = now()
WHERE id = $1
`

type MarkFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) error {
	_, err := q.db.Exec(ctx, markFailed, arg.ID, arg.ErrorMessage)
	return err
}

const updateProgress = `-- name: UpdateProgress :exec
UPDATE jobs
SET status = 'downloading',
    downloaded_bytes = $2,
    total_bytes = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateProgressParams struct {
	ID              pgtype.UUID `json:"id"`
	DownloadedBytes int64       `json:"downloaded_bytes"`
	TotalBytes      pgtype.Int8 `json:"total_bytes"`
}

func (q *Queries) UpdateProgress(ctx context.Context, arg UpdateProgressParams) error {
	_, err := q.db.Exec(ctx, updateProgress, arg.ID, arg.DownloadedBytes, arg.TotalBytes)
	return err
}
